### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#35]
```
Traceback (most recent call last):
  File "BasementRenovatorAfterbirth.py", line 2206, in saveMap
    self.save(self.roomList.getRooms())
  File "BasementRenovatorAfterbirth.py", line 2227, in save
    room.data(0x100).encode(), room.roomWeight, room.roomWidth, room.roomHeight,
 room.roomShape)
struct.error: required argument is not an integer
```

Duplicated a narrow room with exits to the top and bottom. Changed it to have exits to the left and right. Saved, and got a crash.

**Comment by Zamiell** [comment]
Now it crashes when opening the STB:

```
Traceback (most recent call last):
  File "BasementRenovatorAfterbirth.py", line 2113, in openRecent
    rooms = self.open()
  File "BasementRenovatorAfterbirth.py", line 2128, in open
    header = struct.unpack_from('<4s', stb, 0)[0].decode()
struct.error: unpack_from requires a buffer of at least 4 bytes
```

**Comment by Tempus** [comment]
Fixed!
