### ISSUE TITLE
Crash while opening an .stb file

### ISSUE THREAD

**Issue by damexx11** [Tempus/Basement-Renovator#65]
When i want to open the .stb file program crash. Here is log.
Traceback (most recent call last):
  File "BasementRenovatorAfterbirth.py", line 2741, in <module>
  File "BasementRenovatorAfterbirth.py", line 47, in getEntityXML
  File "C:\Python34\lib\xml\etree\ElementTree.py", line 1186, in parse
  File "C:\Python34\lib\xml\etree\ElementTree.py", line 587, in parse
FileNotFoundError: [Errno 2] No such file or directory: 'resources/EntitiesAfterbirth.xml'
Please fix it.

**Comment by Tempus** [comment]
If you're running from source, make sure you run it from within the program directory.

**Comment by damexx11** [comment]
It doesn't work too. I copied it to basement renovator folder and it crash every time.
